### ISSUE TITLE
How does it work on Mac?

### ISSUE THREAD

**Issue by Kito0615** [oxoooo/earthlivejs#1]
how does it work on mac os x?

**Comment by xingrz** [comment]
![2015-12-16 20 22 28](https://cloud.githubusercontent.com/assets/288288/11840693/c95b29c6-a432-11e5-9a64-f44d157db4a2.png)

**Comment by ForrestAlfred** [comment]
建议将用法在README中引用一下, 我还以为是自动设置的呢~~
